# Generated by Django 4.2.2 on 2023-06-23 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnailBirthRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preexisting_snail_amount', models.IntegerField()),
                ('newly_hatched_snails', models.IntegerField()),
                ('birth_rate_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SnailFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumed_on', models.DateTimeField()),
                ('grams_feed_given', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SnailMortalityRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preexisting_snail_amount', models.IntegerField()),
                ('expired_snail_amount', models.IntegerField()),
                ('mortality_rate_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTakenToMature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snail_hatched', models.DateTimeField()),
                ('snail_matured', models.DateTimeField()),
                ('days_to_mature', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SnailPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_birth_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('normalized_mortality_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('snail_birth_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.snailbirthrate')),
                ('snail_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.snailfeed')),
                ('snail_mortality_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.snailmortalityrate')),
                ('time_taken_to_mature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.timetakentomature')),
            ],
        ),
    ]
