# Generated by Django 4.2.2 on 2023-06-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snailbirthrate',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
