# Generated by Django 4.2.2 on 2023-09-09 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snailhatchrate',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
