# Generated by Django 4.2.2 on 2023-06-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snailbirthrate',
            name='birth_rate_percentage',
        ),
        migrations.RemoveField(
            model_name='snailmortalityrate',
            name='mortality_rate_percentage',
        ),
        migrations.RemoveField(
            model_name='timetakentomature',
            name='days_to_mature',
        ),
    ]
