# Generated by Django 4.2.2 on 2023-09-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snailbed',
            name='bed_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='snailhatchrate',
            name='preexisting_snail_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snailmortalityrate',
            name='preexisting_snail_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
