# Generated by Django 4.2.2 on 2023-09-11 16:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snailbedperformance',
            name='expected_time_to_maturity',
        ),
        migrations.RemoveField(
            model_name='snailbedperformance',
            name='snail_feed',
        ),
        migrations.RemoveField(
            model_name='snailbedperformance',
            name='snail_hatch_rate',
        ),
        migrations.RemoveField(
            model_name='snailbedperformance',
            name='snail_mortality_rate',
        ),
        migrations.RemoveField(
            model_name='snailbedperformance',
            name='time_taken_to_mature',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='company_tax_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeuser',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.adminuser'),
        ),
        migrations.AddField(
            model_name='snailbed',
            name='maturity_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.timetakentomature'),
        ),
        migrations.AddField(
            model_name='snailbedperformance',
            name='actual_average_time_to_maturity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='snailbedperformance',
            name='average_hatch_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='snailbedperformance',
            name='average_maturity_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='snailbedperformance',
            name='average_mortality_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='snailbedperformance',
            name='expected_average_time_to_maturity',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='snailbed',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.adminuser'),
        ),
        migrations.AlterField(
            model_name='snailbedperformance',
            name='snail_bed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.snailbed'),
        ),
        migrations.AlterField(
            model_name='snailfeed',
            name='consumed_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='snailhatchrate',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='snailmortalityrate',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ForecastedMortalityRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecasted_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('forecasted_value_pyaf', picklefield.fields.PickledObjectField(editable=False)),
                ('snail_bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.snailbed')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastedMaturityRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecasted_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('forecasted_value_pyaf', picklefield.fields.PickledObjectField(editable=False)),
                ('snail_bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.snailbed')),
            ],
        ),
    ]
