# Generated by Django 4.2.2 on 2023-09-07 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetakentomature',
            name='maturity_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='timetakentomature',
            name='period',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetakentomature',
            name='snails_matured_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timetakentomature',
            name='snail_bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.snailbed'),
        ),
    ]
