# Generated by Django 4.2.2 on 2023-06-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_snailbirthrate_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snailbirthrate',
            name='birth_date',
            field=models.DateTimeField(),
        ),
    ]
