# Generated by Django 4.2.2 on 2023-09-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_snailbedperformance_expected_time_to_maturity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snailbed',
            name='average_hatch_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='snailbed',
            name='average_mortality_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='snailbed',
            name='average_time_to_mature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
