# Generated by Django 4.2.2 on 2023-06-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_snailbirthrate_birth_rate_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snailperformance',
            name='bed_performance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='snailperformance',
            name='expected_time_to_maturity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
