# Generated by Django 4.2.2 on 2023-09-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_snailbed_bed_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snailmortalityrate',
            name='expired_snail_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='snailmortalityrate',
            name='preexisting_snail_amount',
            field=models.IntegerField(default=0),
        ),
    ]
