# Generated by Django 4.2.2 on 2023-09-07 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_timetakentomature_maturity_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snailperformance',
            name='snail_bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.snailbed'),
        ),
        migrations.AlterField(
            model_name='timetakentomature',
            name='maturity_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
