# Generated by Django 4.2.2 on 2023-06-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_snailperformance_bed_performance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecasted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecasted_snail_feed', models.FloatField()),
                ('forecasted_birth_rate', models.FloatField()),
                ('forecasted_mortality_rate', models.FloatField()),
                ('forecasted_time_to_mature', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='snailperformance',
            name='bed_performance',
        ),
    ]
