# Generated by Django 4.2.2 on 2023-09-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_snailperformance_snail_bed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snailperformance',
            name='normalized_hatch_rate',
        ),
        migrations.RemoveField(
            model_name='snailperformance',
            name='normalized_mortality_rate',
        ),
    ]
