# Generated by Django 4.2.2 on 2023-09-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_snailbed_user_snailbed_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snailbed',
            name='user',
        ),
    ]
