# Generated by Django 4.2.2 on 2023-06-24 13:12

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_snailbirthrate_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastedbirthrate',
            name='forecasted_value_pyaf',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
        migrations.AlterField(
            model_name='snailbirthrate',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
