# Generated by Django 4.2.2 on 2023-09-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_snailbed_average_hatch_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snailbed',
            name='average_hatch_rate',
        ),
        migrations.RemoveField(
            model_name='snailbed',
            name='average_mortality_rate',
        ),
        migrations.RemoveField(
            model_name='snailbed',
            name='average_time_to_mature',
        ),
    ]
