# Generated by Django 4.2.2 on 2023-06-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_forecasted_remove_snailperformance_bed_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecasted',
            name='forecasted_birth_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecasted',
            name='forecasted_mortality_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecasted',
            name='forecasted_snail_feed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecasted',
            name='forecasted_time_to_mature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
