# Generated by Django 4.2.2 on 2023-09-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_snailbed_mortality_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snailmortalityrate',
            name='preexisting_snail_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
