# Generated by Django 4.2.2 on 2023-09-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_snailperformance_normalized_hatch_rate_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SnailPerformance',
            new_name='SnailBedPerformance',
        ),
    ]
