# Generated by Django 4.2.2 on 2023-09-04 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_forecastedbirthrate_forecasted_value_pyaf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnailBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('forecasted_birth_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.forecastedbirthrate')),
                ('snail_birth_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.snailbirthrate')),
                ('snail_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.snailfeed')),
                ('snail_mortality_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.snailmortalityrate')),
                ('snail_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.snailperformance')),
                ('time_taken_to_mature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.timetakentomature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
