# Generated by Django 4.2.2 on 2023-09-13 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_snailbed_average_hatch_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snailbed',
            name='snail_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.snailfeed'),
        ),
    ]
