# Generated by Django 4.2.2 on 2023-09-08 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_remove_snailbed_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snailbed',
            name='hatch_rate',
        ),
        migrations.RemoveField(
            model_name='snailbed',
            name='mortality_rate',
        ),
        migrations.AddField(
            model_name='snailbed',
            name='user',
            field=models.ManyToManyField(blank=True, db_constraint=False, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
