# Generated by Django 4.2.2 on 2023-09-09 15:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_snailfeed_consumed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='snailbed',
            name='maturity_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.timetakentomature'),
        ),
        migrations.AddField(
            model_name='timetakentomature',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
