# Generated by Django 4.2.2 on 2023-09-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_snailmortalityrate_preexisting_snail_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snailbed',
            name='mortality_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
