# Generated by Django 4.2.2 on 2023-09-08 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_snailbed_hatch_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snailbed',
            name='hatch_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.snailhatchrate'),
        ),
        migrations.AddField(
            model_name='snailbed',
            name='mortality_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.snailmortalityrate'),
        ),
    ]
