# Generated by Django 4.2.2 on 2023-09-07 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_snailperformance_snailbedperformance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastedhatchrate',
            name='snail_bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.snailbed'),
        ),
    ]
