# Generated by Django 4.2.2 on 2023-09-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_snailbed_maturity_rate_timetakentomature_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetakentomature',
            name='datetime',
        ),
    ]
