# Generated by Django 4.2.2 on 2023-09-07 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_forecastedhatchrate_snail_bed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snailhatchrate',
            name='datetime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='snailmortalityrate',
            name='datetime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
