# Generated by Django 4.2.2 on 2023-09-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_timetakentomature_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snailbedperformance',
            name='expected_time_to_maturity',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
    ]
