# Generated by Django 4.2.2 on 2023-06-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_forecastedbirthrate_delete_forecasted'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastedbirthrate',
            name='forecasted_value_pyaf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='forecastedbirthrate',
            name='forecasted_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
