# Generated by Django 4.2.2 on 2023-09-06 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_snailbed_bed_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForecastedBirthRate',
            new_name='ForecastedHatchRate',
        ),
        migrations.RenameModel(
            old_name='SnailBirthRate',
            new_name='SnailHatchRate',
        ),
        migrations.RenameField(
            model_name='snailbed',
            old_name='forecasted_birth_rate',
            new_name='forecasted_hatch_rate',
        ),
        migrations.RenameField(
            model_name='snailbed',
            old_name='snail_birth_rate',
            new_name='snail_hatch_rate',
        ),
        migrations.RenameField(
            model_name='snailhatchrate',
            old_name='birth_date',
            new_name='hatch_date',
        ),
        migrations.RenameField(
            model_name='snailperformance',
            old_name='normalized_birth_rate',
            new_name='normalized_hatch_rate',
        ),
        migrations.RenameField(
            model_name='snailperformance',
            old_name='snail_birth_rate',
            new_name='snail_hatch_rate',
        ),
    ]
