# Generated by Django 4.2.2 on 2023-09-09 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_snailbedperformance_expected_time_to_maturity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snailbedperformance',
            name='snail_bed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.snailbed'),
        ),
    ]
