# Generated by Django 4.2.2 on 2023-09-08 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_snailbed_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snailbed',
            name='user',
        ),
        migrations.AddField(
            model_name='snailbed',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile'),
        ),
    ]
