# Generated by Django 4.2.2 on 2023-09-07 18:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_hatchratefeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hatchratefeed',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='snailfeed',
            name='consumed_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='snailfeed',
            name='snail_bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.snailbed'),
        ),
    ]
