# Generated by Django 4.2.2 on 2023-09-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_snailbedperformance_snail_bed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snailbedperformance',
            name='snail_feed',
        ),
        migrations.RemoveField(
            model_name='snailbedperformance',
            name='snail_hatch_rate',
        ),
        migrations.RemoveField(
            model_name='snailbedperformance',
            name='snail_mortality_rate',
        ),
        migrations.RemoveField(
            model_name='snailbedperformance',
            name='time_taken_to_mature',
        ),
        migrations.AddField(
            model_name='snailbedperformance',
            name='average_hatch_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='snailbedperformance',
            name='average_maturity_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='snailbedperformance',
            name='average_mortality_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
