# Generated by Django 4.2.2 on 2023-09-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_snailbedperformance_snail_feed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snailbedperformance',
            name='expected_time_to_maturity',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
