# Generated by Django 4.2.2 on 2023-09-06 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_snailbed_snail_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snailbed',
            name='mortality_rate',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.snailmortalityrate'),
        ),
    ]
