# Generated by Django 4.2.2 on 2023-09-07 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_hatchratefeed_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hatchratefeed',
            old_name='timestamp',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='hatchratefeed',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
