# Generated by Django 4.2.2 on 2023-09-06 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_snailbed_mortality_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snailmortalityrate',
            name='snail_bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.snailbed'),
        ),
    ]
