# Generated by Django 4.2.2 on 2023-09-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_snailbedperformance_expected_time_to_maturity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snailbedperformance',
            name='expected_time_to_maturity',
        ),
        migrations.AddField(
            model_name='snailbedperformance',
            name='actual_average_time_to_maturity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='snailbedperformance',
            name='expected_average_time_to_maturity',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
