# Generated by Django 4.2.2 on 2023-09-09 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_snailbedperformance_expected_time_to_maturity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snailhatchrate',
            name='datefield',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
