# Generated by Django 4.2.2 on 2023-09-09 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_snailhatchrate_datefield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snailhatchrate',
            name='datefield',
        ),
    ]
