# Generated by Django 4.2.2 on 2023-09-11 11:03

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_snailhatchrate_datefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastedMortalityRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecasted_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('forecasted_value_pyaf', picklefield.fields.PickledObjectField(editable=False)),
                ('snail_bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.snailbed')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastedMaturityRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecasted_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('forecasted_value_pyaf', picklefield.fields.PickledObjectField(editable=False)),
                ('snail_bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.snailbed')),
            ],
        ),
    ]
