# Generated by Django 4.2.2 on 2023-09-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_forecastedmortalityrate_forecastedmaturityrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='business_name',
            field=models.CharField(default='test', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminuser',
            name='company_tax_code',
            field=models.CharField(default='test', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminuser',
            name='first_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminuser',
            name='surname',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
