# Generated by Django 4.2.2 on 2023-09-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_adminuser_business_name_adminuser_company_tax_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='surname',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='company_tax_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
